// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type NewTodo struct {
	Text string `json:"text"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}
