// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo/v1beta1/todo.proto

package todov1beta1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Todo is a note describing a task to be done.
type Todo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_35cc472031576912, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Todo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*Todo)(nil), "todo.v1beta1.Todo")
}

func init() {
	proto.RegisterFile("todo/v1beta1/todo.proto", fileDescriptor_35cc472031576912)
}

var fileDescriptor_35cc472031576912 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x07, 0x71, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x78, 0xc0, 0x6c, 0xa8, 0x84, 0x92, 0x1d, 0x17, 0x4b, 0x48, 0x7e, 0x4a, 0xbe, 0x10,
	0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90,
	0x10, 0x17, 0x4b, 0x49, 0x6a, 0x45, 0x89, 0x04, 0x13, 0x58, 0x04, 0xcc, 0x06, 0x89, 0xa5, 0xe4,
	0xe7, 0xa5, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x04, 0x81, 0xd9, 0x4e, 0x01, 0x5c, 0x02, 0xc9,
	0xf9, 0xb9, 0x7a, 0xc8, 0x66, 0x3a, 0x71, 0x82, 0x4c, 0x0c, 0x00, 0x59, 0x16, 0xc0, 0x18, 0xc5,
	0x0d, 0x92, 0x82, 0xca, 0x2c, 0x62, 0x62, 0x0e, 0x89, 0x88, 0x58, 0xc5, 0xc4, 0x03, 0x52, 0xa0,
	0x17, 0x66, 0xe8, 0x04, 0x12, 0x3c, 0x05, 0xe1, 0xc6, 0x40, 0xb9, 0x49, 0x6c, 0x60, 0x67, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x49, 0xd1, 0x8e, 0xc1, 0x00, 0x00, 0x00,
}
