// Code generated by entc, DO NOT EDIT.

package todoitem

import (
	"time"
)

const (
	// Label holds the string label denoting the todoitem type in the database.
	Label = "todo_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldUID holds the string denoting the uid vertex property in the database.
	FieldUID       = "uid"        // FieldTitle holds the string denoting the title vertex property in the database.
	FieldTitle     = "title"      // FieldCompleted holds the string denoting the completed vertex property in the database.
	FieldCompleted = "completed"  // FieldOrder holds the string denoting the order vertex property in the database.
	FieldOrder     = "order"      // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the todoitem in the database.
	Table = "todo_items"
)

// Columns holds all SQL columns for todoitem fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldTitle,
	FieldCompleted,
	FieldOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	UIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
