/*
 * Hello World API
 *
 * Some description
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Hello struct {

	Message string `json:"message,omitempty"`
}
