run:
    skip-dirs:
        - .gen

linters:
    enable-all: true
    disable:
        - maligned

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/modern-go-application
