version: "3.1"

services:
    db:
        image: mysql:8.0
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: app

    dockerhost:
        image: qoomon/docker-host:2.3.0
        cap_add: [ 'NET_ADMIN', 'NET_RAW' ]

    prometheus:
        image: prom/prometheus:v2.12.0
        volumes:
            - ./etc/local/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--storage.tsdb.retention=200h'
            - '--web.enable-lifecycle'

    grafana:
        image: grafana/grafana:6.3.3
        depends_on:
            - prometheus
        environment:
            GF_USERS_ALLOW_SIGN_UP: "false"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
        volumes:
            - ./etc/local/grafana/provisioning:/etc/grafana/provisioning

    jaeger:
        image: jaegertracing/all-in-one:1.13.1

    oc-collector:
        image: omnition/opencensus-collector:0.1.10
        command: ["--config=/etc/opencensus/collector.yaml"]
        volumes:
            - ./etc/local/opencensus/:/etc/opencensus/:ro
        depends_on:
            - jaeger

    oc-agent:
        image: omnition/opencensus-agent:0.1.10
        command: ["--config=/etc/opencensus/agent.yaml"]
        volumes:
            - ./etc/local/opencensus/:/etc/opencensus/:ro
        depends_on:
            - oc-collector
