FROM alpine:3.7 AS builder

RUN apk add --update --no-cache ca-certificates


FROM alpine:3.7

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG BUILD_DIR
ARG BINARY_NAME

COPY $BUILD_DIR/$BINARY_NAME /service

EXPOSE 8000 10000
CMD ["/service", "--instrument-addr", ":10000", "--http-addr", ":8000"]
