FROM alpine:3.9

RUN apk add --update --no-cache ca-certificates tzdata

ARG BUILD_DIR
ARG BINARY_NAME

COPY $BUILD_DIR/$BINARY_NAME /app

EXPOSE 8000 10000
CMD ["/app", "--instrumentation.addr", ":10000", "--app.addr", ":8000"]
