// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
