// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// TodoItem is the predicate function for todoitem builders.
type TodoItem func(*sql.Selector)
