/*
 * Hello World API
 *
 * Some description
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type HelloRequest struct {

	Greeting string `json:"greeting,omitempty"`
}
