// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/migrate"

	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/todoitem"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// TodoItem is the client for interacting with the TodoItem builders.
	TodoItem *TodoItemClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.TodoItem = NewTodoItemClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		TodoItem: NewTodoItemClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:   cfg,
		TodoItem: NewTodoItemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		TodoItem.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.TodoItem.Use(hooks...)
}

// TodoItemClient is a client for the TodoItem schema.
type TodoItemClient struct {
	config
}

// NewTodoItemClient returns a client for the TodoItem from the given config.
func NewTodoItemClient(c config) *TodoItemClient {
	return &TodoItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `todoitem.Hooks(f(g(h())))`.
func (c *TodoItemClient) Use(hooks ...Hook) {
	c.hooks.TodoItem = append(c.hooks.TodoItem, hooks...)
}

// Create returns a create builder for TodoItem.
func (c *TodoItemClient) Create() *TodoItemCreate {
	mutation := newTodoItemMutation(c.config, OpCreate)
	return &TodoItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TodoItem entities.
func (c *TodoItemClient) CreateBulk(builders ...*TodoItemCreate) *TodoItemCreateBulk {
	return &TodoItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TodoItem.
func (c *TodoItemClient) Update() *TodoItemUpdate {
	mutation := newTodoItemMutation(c.config, OpUpdate)
	return &TodoItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TodoItemClient) UpdateOne(ti *TodoItem) *TodoItemUpdateOne {
	mutation := newTodoItemMutation(c.config, OpUpdateOne, withTodoItem(ti))
	return &TodoItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TodoItemClient) UpdateOneID(id int) *TodoItemUpdateOne {
	mutation := newTodoItemMutation(c.config, OpUpdateOne, withTodoItemID(id))
	return &TodoItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TodoItem.
func (c *TodoItemClient) Delete() *TodoItemDelete {
	mutation := newTodoItemMutation(c.config, OpDelete)
	return &TodoItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TodoItemClient) DeleteOne(ti *TodoItem) *TodoItemDeleteOne {
	return c.DeleteOneID(ti.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TodoItemClient) DeleteOneID(id int) *TodoItemDeleteOne {
	builder := c.Delete().Where(todoitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TodoItemDeleteOne{builder}
}

// Query returns a query builder for TodoItem.
func (c *TodoItemClient) Query() *TodoItemQuery {
	return &TodoItemQuery{
		config: c.config,
	}
}

// Get returns a TodoItem entity by its id.
func (c *TodoItemClient) Get(ctx context.Context, id int) (*TodoItem, error) {
	return c.Query().Where(todoitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TodoItemClient) GetX(ctx context.Context, id int) *TodoItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TodoItemClient) Hooks() []Hook {
	return c.hooks.TodoItem
}
