// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/schema"
	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/todoitem"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoitemFields := schema.TodoItem{}.Fields()
	_ = todoitemFields
	// todoitemDescUID is the schema descriptor for uid field.
	todoitemDescUID := todoitemFields[0].Descriptor()
	// todoitem.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	todoitem.UIDValidator = func() func(string) error {
		validators := todoitemDescUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(uid string) error {
			for _, fn := range fns {
				if err := fn(uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// todoitemDescCreatedAt is the schema descriptor for created_at field.
	todoitemDescCreatedAt := todoitemFields[4].Descriptor()
	// todoitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	todoitem.DefaultCreatedAt = todoitemDescCreatedAt.Default.(func() time.Time)
	// todoitemDescUpdatedAt is the schema descriptor for updated_at field.
	todoitemDescUpdatedAt := todoitemFields[5].Descriptor()
	// todoitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todoitem.DefaultUpdatedAt = todoitemDescUpdatedAt.Default.(func() time.Time)
	// todoitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todoitem.UpdateDefaultUpdatedAt = todoitemDescUpdatedAt.UpdateDefault.(func() time.Time)
}
