// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/todoitem"
)

// TodoItem is the model entity for the TodoItem schema.
type TodoItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UID holds the value of the "uid" field.
	UID string `json:"uid,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Completed holds the value of the "completed" field.
	Completed bool `json:"completed,omitempty"`
	// Order holds the value of the "order" field.
	Order int `json:"order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TodoItem) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // uid
		&sql.NullString{}, // title
		&sql.NullBool{},   // completed
		&sql.NullInt64{},  // order
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TodoItem fields.
func (ti *TodoItem) assignValues(values ...interface{}) error {
	if m, n := len(values), len(todoitem.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ti.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field uid", values[0])
	} else if value.Valid {
		ti.UID = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field title", values[1])
	} else if value.Valid {
		ti.Title = value.String
	}
	if value, ok := values[2].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field completed", values[2])
	} else if value.Valid {
		ti.Completed = value.Bool
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field order", values[3])
	} else if value.Valid {
		ti.Order = int(value.Int64)
	}
	if value, ok := values[4].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[4])
	} else if value.Valid {
		ti.CreatedAt = value.Time
	}
	if value, ok := values[5].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[5])
	} else if value.Valid {
		ti.UpdatedAt = value.Time
	}
	return nil
}

// Update returns a builder for updating this TodoItem.
// Note that, you need to call TodoItem.Unwrap() before calling this method, if this TodoItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (ti *TodoItem) Update() *TodoItemUpdateOne {
	return (&TodoItemClient{config: ti.config}).UpdateOne(ti)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ti *TodoItem) Unwrap() *TodoItem {
	tx, ok := ti.config.driver.(*txDriver)
	if !ok {
		panic("ent: TodoItem is not a transactional entity")
	}
	ti.config.driver = tx.drv
	return ti
}

// String implements the fmt.Stringer.
func (ti *TodoItem) String() string {
	var builder strings.Builder
	builder.WriteString("TodoItem(")
	builder.WriteString(fmt.Sprintf("id=%v", ti.ID))
	builder.WriteString(", uid=")
	builder.WriteString(ti.UID)
	builder.WriteString(", title=")
	builder.WriteString(ti.Title)
	builder.WriteString(", completed=")
	builder.WriteString(fmt.Sprintf("%v", ti.Completed))
	builder.WriteString(", order=")
	builder.WriteString(fmt.Sprintf("%v", ti.Order))
	builder.WriteString(", created_at=")
	builder.WriteString(ti.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(ti.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TodoItems is a parsable slice of TodoItem.
type TodoItems []*TodoItem

func (ti TodoItems) config(cfg config) {
	for _i := range ti {
		ti[_i].config = cfg
	}
}
