/*
 * Todo API
 *
 * Manage TODOs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type TodoList struct {

	Todos []Todo `json:"todos,omitempty"`
}
