/*
 * Todo API
 *
 * Manage TODOs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Todo struct {

	Id string `json:"id"`

	Text string `json:"text"`

	Done bool `json:"done"`
}
