/*
 * Todo API
 *
 * Manage TODOs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Todo struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Completed bool `json:"completed,omitempty"`
}
