/*
 * Todo API
 *
 * Manage TODOs
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type UpdateTodoRequest struct {

	Title *string `json:"title,omitempty"`

	Completed *bool `json:"completed,omitempty"`
}
