// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package tododriver

import (
	"context"
	"errors"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CreateTodo     endpoint.Endpoint
	DeleteAll      endpoint.Endpoint
	DeleteItem     endpoint.Endpoint
	GetItem        endpoint.Endpoint
	ListTodos      endpoint.Endpoint
	MarkAsComplete endpoint.Endpoint
	UpdateItem     endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service todo.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{
		CreateTodo:     kitxendpoint.OperationNameMiddleware("todo.CreateTodo")(mw(MakeCreateTodoEndpoint(service))),
		DeleteAll:      kitxendpoint.OperationNameMiddleware("todo.DeleteAll")(mw(MakeDeleteAllEndpoint(service))),
		DeleteItem:     kitxendpoint.OperationNameMiddleware("todo.DeleteItem")(mw(MakeDeleteItemEndpoint(service))),
		GetItem:        kitxendpoint.OperationNameMiddleware("todo.GetItem")(mw(MakeGetItemEndpoint(service))),
		ListTodos:      kitxendpoint.OperationNameMiddleware("todo.ListTodos")(mw(MakeListTodosEndpoint(service))),
		MarkAsComplete: kitxendpoint.OperationNameMiddleware("todo.MarkAsComplete")(mw(MakeMarkAsCompleteEndpoint(service))),
		UpdateItem:     kitxendpoint.OperationNameMiddleware("todo.UpdateItem")(mw(MakeUpdateItemEndpoint(service))),
	}
}

// CreateTodoRequest is a request struct for CreateTodo endpoint.
type CreateTodoRequest struct {
	Title string
}

// CreateTodoResponse is a response struct for CreateTodo endpoint.
type CreateTodoResponse struct {
	Todo todo.Todo
	Err  error
}

func (r CreateTodoResponse) Failed() error {
	return r.Err
}

// MakeCreateTodoEndpoint returns an endpoint for the matching method of the underlying service.
func MakeCreateTodoEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(CreateTodoRequest)

		todo, err := service.CreateTodo(ctx, req.Title)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return CreateTodoResponse{
					Err:  err,
					Todo: todo,
				}, nil
			}

			return CreateTodoResponse{
				Err:  err,
				Todo: todo,
			}, err
		}

		return CreateTodoResponse{Todo: todo}, nil
	}
}

// DeleteAllRequest is a request struct for DeleteAll endpoint.
type DeleteAllRequest struct{}

// DeleteAllResponse is a response struct for DeleteAll endpoint.
type DeleteAllResponse struct {
	Err error
}

func (r DeleteAllResponse) Failed() error {
	return r.Err
}

// MakeDeleteAllEndpoint returns an endpoint for the matching method of the underlying service.
func MakeDeleteAllEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		err := service.DeleteAll(ctx)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return DeleteAllResponse{Err: err}, nil
			}

			return DeleteAllResponse{Err: err}, err
		}

		return DeleteAllResponse{}, nil
	}
}

// DeleteItemRequest is a request struct for DeleteItem endpoint.
type DeleteItemRequest struct {
	Id string
}

// DeleteItemResponse is a response struct for DeleteItem endpoint.
type DeleteItemResponse struct {
	Err error
}

func (r DeleteItemResponse) Failed() error {
	return r.Err
}

// MakeDeleteItemEndpoint returns an endpoint for the matching method of the underlying service.
func MakeDeleteItemEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(DeleteItemRequest)

		err := service.DeleteItem(ctx, req.Id)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return DeleteItemResponse{Err: err}, nil
			}

			return DeleteItemResponse{Err: err}, err
		}

		return DeleteItemResponse{}, nil
	}
}

// GetItemRequest is a request struct for GetItem endpoint.
type GetItemRequest struct {
	Id string
}

// GetItemResponse is a response struct for GetItem endpoint.
type GetItemResponse struct {
	Todo todo.Todo
	Err  error
}

func (r GetItemResponse) Failed() error {
	return r.Err
}

// MakeGetItemEndpoint returns an endpoint for the matching method of the underlying service.
func MakeGetItemEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(GetItemRequest)

		todo, err := service.GetItem(ctx, req.Id)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return GetItemResponse{
					Err:  err,
					Todo: todo,
				}, nil
			}

			return GetItemResponse{
				Err:  err,
				Todo: todo,
			}, err
		}

		return GetItemResponse{Todo: todo}, nil
	}
}

// ListTodosRequest is a request struct for ListTodos endpoint.
type ListTodosRequest struct{}

// ListTodosResponse is a response struct for ListTodos endpoint.
type ListTodosResponse struct {
	Todos []todo.Todo
	Err   error
}

func (r ListTodosResponse) Failed() error {
	return r.Err
}

// MakeListTodosEndpoint returns an endpoint for the matching method of the underlying service.
func MakeListTodosEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		todos, err := service.ListTodos(ctx)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return ListTodosResponse{
					Err:   err,
					Todos: todos,
				}, nil
			}

			return ListTodosResponse{
				Err:   err,
				Todos: todos,
			}, err
		}

		return ListTodosResponse{Todos: todos}, nil
	}
}

// MarkAsCompleteRequest is a request struct for MarkAsComplete endpoint.
type MarkAsCompleteRequest struct {
	Id string
}

// MarkAsCompleteResponse is a response struct for MarkAsComplete endpoint.
type MarkAsCompleteResponse struct {
	Err error
}

func (r MarkAsCompleteResponse) Failed() error {
	return r.Err
}

// MakeMarkAsCompleteEndpoint returns an endpoint for the matching method of the underlying service.
func MakeMarkAsCompleteEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(MarkAsCompleteRequest)

		err := service.MarkAsComplete(ctx, req.Id)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return MarkAsCompleteResponse{Err: err}, nil
			}

			return MarkAsCompleteResponse{Err: err}, err
		}

		return MarkAsCompleteResponse{}, nil
	}
}

// UpdateItemRequest is a request struct for UpdateItem endpoint.
type UpdateItemRequest struct {
	Id        string
	Title     *string
	Completed *bool
}

// UpdateItemResponse is a response struct for UpdateItem endpoint.
type UpdateItemResponse struct {
	Todo todo.Todo
	Err  error
}

func (r UpdateItemResponse) Failed() error {
	return r.Err
}

// MakeUpdateItemEndpoint returns an endpoint for the matching method of the underlying service.
func MakeUpdateItemEndpoint(service todo.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(UpdateItemRequest)

		todo, err := service.UpdateItem(ctx, req.Id, req.Title, req.Completed)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return UpdateItemResponse{
					Err:  err,
					Todo: todo,
				}, nil
			}

			return UpdateItemResponse{
				Err:  err,
				Todo: todo,
			}, err
		}

		return UpdateItemResponse{Todo: todo}, nil
	}
}
