// Code generated by entc, DO NOT EDIT.

package todo

import (
	"time"

	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/schema"
)

const (
	// Label holds the string label denoting the todo type in the database.
	Label = "todo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid vertex property in the database.
	FieldUID = "uid"
	// FieldText holds the string denoting the text vertex property in the database.
	FieldText = "text"
	// FieldDone holds the string denoting the done vertex property in the database.
	FieldDone = "done"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the todo in the database.
	Table = "todos"
)

// Columns holds all SQL columns for todo fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldText,
	FieldDone,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	fields = schema.Todo{}.Fields()

	// descUID is the schema descriptor for uid field.
	descUID = fields[0].Descriptor()
	// UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	UIDValidator = func() func(string) error {
		validators := descUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(uid string) error {
			for _, fn := range fns {
				if err := fn(uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()

	// descCreatedAt is the schema descriptor for created_at field.
	descCreatedAt = fields[3].Descriptor()
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt = descCreatedAt.Default.(func() time.Time)

	// descUpdatedAt is the schema descriptor for updated_at field.
	descUpdatedAt = fields[4].Descriptor()
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt = descUpdatedAt.Default.(func() time.Time)
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt = descUpdatedAt.UpdateDefault.(func() time.Time)
)
