// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todoadapter/ent/runtime.go

const (
	Version = "v0.2.1"                                          // Version of ent codegen.
	Sum     = "h1:l8Au/k8u2r+qfuk5Cq5MJwq75gv1necDQeHWysZFcO4=" // Sum of ent codegen.
)
