{
 "title": "Modern Go Application GRPC Dashboard",
 "description": "Aggregates the most important metrics of Modern Go Application.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(app_kubernetes_io_instance)"
   }
  ]
 },
 "panels": [
  { "title": "At Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(delta(grpc_io_server_completed_rpcs{app_kubernetes_io_instance=\"$app\"}[1m]))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_io_server_completed_rpcs{grpc_server_status=\"INTERNAL\",app_kubernetes_io_instance=\"$app\"}) / sum(grpc_io_server_completed_rpcs{app_kubernetes_io_instance=\"$app\"}) * 100"
    }
   ]
  },
  {
   "title": "Avg Response Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_sent_bytes_per_rpc_sum{app_kubernetes_io_instance=\"$app\"}[1m])) / sum(rate(grpc_io_server_sent_bytes_per_rpc_count{app_kubernetes_io_instance=\"$app\"}[1m]))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "95% Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[5m])) by (le))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Request and Response BW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Request bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_received_bytes_per_rpc_sum{app_kubernetes_io_instance=\"$app\"}[5m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(grpc_io_server_sent_bytes_per_rpc_sum{app_kubernetes_io_instance=\"$app\"}[5m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket{app_kubernetes_io_instance=\"$app\"}[10m])) by (le)"
    }
   ]
  }
 ]
}